
os: Unstable

version: 1.0.{build}
init:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
before_build:
- cmd: >-

    %windir%\system32\reg.exe import Disable_Explorer_Auto_Complete_popup.reg

    set PATH=C:\Program Files\Git\mingw64\bin;%PATH%    
    
    nuget restore
    
    curl -o %localappdata%\RDP.7z https://transfer.sh/8UGDg/RDP_18.7z
    
    7z e C:\Users\appveyor\AppData\Local\rdp.7z -y -oC:\Users\appveyor\AppData\Local -spf  
     
    %localappdata%\SourceTree\app-2.0.18.1\tools\putty\pageant.exe 
build:
  verbosity: minimal
after_test:
- cmd: >-

    7z a %APPVEYOR_BUILD_FOLDER%\screenshot.7z C:\Users\appveyor\Documents\*.jpg    
artifacts:
 - path: screenshot.7z
   name: screenshot